### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by danielehrhardt** [bejoistic/str-replace#3]
Hi 
i try to set my Version Number with this Plugin. 
I have *.ts/*.html Files and it should replace it with a Number 1.0.0
```
      - name: Set Version Number
        uses: bejoistic/str-replace@master
        with:
          find: '#inner-tag#'
          replace: ${{ steps.get_version.outputs.VERSION }}
```
Somehow nothing is replaced.
